# Puerto del servidor web
server.port=8080

# ==========================================
# CONFIGURACIÓN PARA POSTGRESQL EN LA NUBE (Render)
# ==========================================
spring.datasource.url=jdbc:postgresql://dpg-d8vgbcernols73dm1c20-a.ohio-postgres.render.com/emergencias_db_35cf?sslmode=require
spring.datasource.username=admin911
spring.datasource.password=6jT6OCDfo0JfvKoxbcfBxa2vChVTu2ku
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (Manejo de tablas automático)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
